%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 400
image_height: 208
distortion_parameters:
   k1: 0
   k2: 0
   p1: 0
   p2: 0
projection_parameters:
   fx: 200
   fy: 200
   cx: 200
   cy: 104